### PR TITLE
New project structure

### PR DESCRIPTION
**Pull request by HomerusJa**
This pull request contains the project structure needed for the new architecture discussed in #31 

## General Changes

- Introduce seperation of frontend and backend
- Introduce Docker (files still empty)
- Created docs section which outlines the targeted architecture and design decisions made

## Frontend Changes

I didnt touch the frontend as this is not my area of expertise.

### Switch to uv as a package manager

I switched from Poetry to [uv](https://docs.astral.sh/uv/) as a package manager, as it is the current best solution. Following a comparison between uv and poetry:

#### Benefits of uv
- **Speed**: Faster installation and resolution due to Rust implementation.
- **Simplicity**: Easy transition from pip with a straightforward interface.
- **Unified Tooling**: Combines multiple tasks into one tool.

#### Drawbacks of uv
- **Limited Features**: Lacks some advanced features found in poetry.
- **Maturity**: Newer tool with potentially less stability and documentation.
- **Compatibility Issues**: May require adjustments for existing poetry projects.

#### Benefits of Poetry
- **Comprehensive Management**: Excellent dependency resolution and handling.
- **Native Dependency Support**: Better for projects needing compiled modules.
- **Established Ecosystem**: Strong community support and extensive documentation.

#### Drawbacks of Poetry
- **Performance Overhead**: Slower than uv in some cases.
- **Complexity**: More features can lead to unnecessary complexity for simple projects.

### Add Ruff for linting

I added Ruff and some basic ruff config as a python linter as it is the commonly agreed best linter currently available. Some reasons on why to use Ruff:

- **Speed**: 10-100x faster than traditional linters.
- **Consolidation**: Replaces multiple tools (e.g., Flake8, isort) in one package.
- **Feature Parity**: Offers a wide range of checks for style and security.
- **Configurability**: Easy setup via `pyproject.toml`.
- **Community Adoption**: Increasingly used by popular projects like FastAPI or pandas.

## Github Action Changes

- Put all autocomments in one action `autocomment-on-events.yml` to clean up the action directory
- Added Ruff formatting
- Added pytest testing

## Todos

I think those can be put in different issues and handled seperately. This list is not comprehensive.

- [ ] Fill the .gitignore
- [ ] Update the CONTRIBUTING.md and the README.md
- [ ] Create the Docker deployments
- [ ] Finish documenting the architecture
- [ ] Add the frontend structure
- [ ] Implement the frontend
- [ ] Implement the backend

### CODE REVIEW

**Comment by HomerusJa** [comment]
Also added the logos as in the repository.

**Comment by HomerusJa** [comment]
@dmotts @swarupn17 @shawaiz-khan @Brijeshthummar02 @team What do you think about these changes?

**Comment by dmotts** [comment]
@HomerusJa Tremendous work 👏! I'll push your work and we'll try to get a demo up as soon as possible.

**Comment by HomerusJa** [comment]
I can do that, however, the .idea folder only contains IDE-specific settings and there is no risk at all of submitting API keys. If you dont want to have any IDE settings in this repository, we should communicate that clearly.

**Review by dmotts — APPROVED** [review]

**Comment by HomerusJa** [comment]
Ima create issues for the different tasks mentioned above.

**Comment by Brijeshthummar02** [comment]
@HomerusJa that would be easy to assist.

**Comment by HomerusJa** [comment]
Can you start from the bottom?

**Pull request merged**
