### PR TITLE
Add the requirements-autoupdate workflow, add type hints and fix crash when no client secrets file is provided

### PR DESCRIPTION
**Pull request by HomerusJa**
**EDIT**: I programmed further in my fork and thought I could open a new pull request, but apperently I cannot (or I am too dumb to find the option). This pull request should be split into three, but I dont know how.

As described in #9, here is the workflow.

Changes made since suggestion:
  - Added workflow_dispatch trigger to allow manual run

### CODE REVIEW

**Comment by HomerusJa** [comment]
We might also want to add an autoupdater to the lock-file using poetry lock

**Comment by HomerusJa** [comment]
Or does that kinda defeat the whole purpose of a lockfile?

**Comment by HomerusJa** [comment]
I am also thinking about letting ruff or so run to autoformat the code...

**Comment by dmotts** [comment]
Alright @HomerusJa we'll figure it out! Is the '.idea' directory necessary for the app to run remotely or is it for your local machine's IDE?

**Comment by HomerusJa** [comment]
The .idea folder contains Jetbrains configuration files. If you want, we can just throw it out. I'd rather opt of a more gentle solution using the updated .gitignore as like that, the IDE settings are kept, but this is your project. Do as you wish!

**Comment by dmotts** [comment]
@HomerusJa I am not sorry to say but this is no longer "my" project 😆. We could add it to the .gitignore. That should work!

**Comment by HomerusJa** [comment]
Also, I just remembered I also added methods to download subtitles as in #11 
It is not fully integrated in the UI nor is it tested.

**Comment by dmotts** [comment]
Great! In that case, I'll assign the task to you. If you require assistance on that particular task #11. Feel free to leave a comment or create another [issue](https://github.com/dmotts/yt-to-cloud-uploader/issues/new?assignees=&labels=enhancement&projects=&template=feature_request.yml&title=%5BFeature+Request%5D+). For now I'll leave the 'help wanted' tag on whilst it's assigned to you.

**Pull request closed without merging**
