### PR TITLE
issue:43 [Documentation Update] : added the technologies.md 

### PR DESCRIPTION
**Pull request by KrinsKumar**
This PR addresses #43 

The following files were added:
- docs/technologies.md - contains all the documentation for tech stack of the project
- public/tech.svg - an architecture diagram referred in the documentation 

Let me know if there are any questions or further adjustments needed.

### CODE REVIEW

**Comment by dmotts** [comment]
Thank you so much for your contribution @KrinsKumar!

**Comment by dmotts** [comment]
Message if you are interested in joining our private Discord server. 

We would be glad for you to join us @KrinsKumar! 😄

**Comment by KrinsKumar** [comment]
Thank you, sure I would love to join!!

**Comment by dmotts** [comment]
> Thank you, sure I would love to join!!

Awesome! 😃

**Pull request merged**
