### PR TITLE
feat: Logo design added

### PR DESCRIPTION
**Pull request by shawaiz-khan**
This pull request adds new logo designs to the project. The logos are in the public folder, and there are a few versions to choose from:

- Logo-01.jpg
- Logo-1.png
- Logo-2.png
- Logo-3.png
- These logos can be used for the app or any branding needs.

Let me know if any changes are needed!

### CODE REVIEW

**Comment by dmotts** [comment]
I love it! 🫶 

Thank you for contributing @shawaiz-khan!

**Comment by shawaiz-khan** [comment]
Thank You! please make this PR hacktoberfest-accepted.

**Comment by dmotts** [comment]
No, thank you Mr. @shawaiz-khan! 

As part of improving and making this project a enjoyable one for all, I ask that you share your opinions in our [discussions](https://github.com/dmotts/yt-to-cloud-uploader/discussions) section.

This will not only help the project grow but it will help all of us grow as a people.

Thanks again, @shawaiz-khan and keep doing you!

**Comment by shawaiz-khan** [comment]
> No, thank you Mr. @shawaiz-khan!
> 
> As part of improving and making this project an enjoyable one for all, I ask that you share your opinions in our [discussions](https://github.com/dmotts/yt-to-cloud-uploader/discussions) section.
> 
> This will not only help the project grow but it will help all of us grow as a people.
> 
> Thanks again, @shawaiz-khan and keep doing you!

Sure

**Pull request merged**
